/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package maestros;

import java.io.File;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author prof_tes_a
 */
public class RopMaeLisRop extends javax.swing.JInternalFrame
{
    private Vector<String> vecNom, vecMar;
    
    /**
     * Creates new form RopMaeLisRop
     */
    public RopMaeLisRop()
    {
        initComponents();
        vecNom=new Vector<String>();
        vecMar=new Vector<String>();
        lstNom.setListData(vecNom);
        lstMar.setListData(vecMar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstNom = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstMar = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        butAbr = new javax.swing.JButton();
        butGua = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Listado de ropa");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        lstNom.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstNom.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstNomValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstNom);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Marca"));
        jPanel2.setPreferredSize(new java.awt.Dimension(150, 231));
        jPanel2.setLayout(new java.awt.BorderLayout());

        lstMar.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstMar.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstMarValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstMar);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        jPanel3.setPreferredSize(new java.awt.Dimension(384, 40));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        butAbr.setText("Abrir");
        butAbr.setPreferredSize(new java.awt.Dimension(100, 30));
        butAbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAbrActionPerformed(evt);
            }
        });
        jPanel3.add(butAbr);

        butGua.setText("Guardar");
        butGua.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel3.add(butGua);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        setBounds(0, 0, 400, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void butAbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAbrActionPerformed
        abrirListadoRopa();
    }//GEN-LAST:event_butAbrActionPerformed

    private void lstNomValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstNomValueChanged
        lstMar.setSelectedIndex(lstNom.getSelectedIndex());
    }//GEN-LAST:event_lstNomValueChanged

    private void lstMarValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstMarValueChanged
        lstNom.setSelectedIndex(lstMar.getSelectedIndex());
    }//GEN-LAST:event_lstMarValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAbr;
    private javax.swing.JButton butGua;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstMar;
    private javax.swing.JList lstNom;
    // End of variables declaration//GEN-END:variables

    private boolean abrirListadoRopa()
    {
        boolean blnRes=true;
        try
        {
            String strArc;
            JFileChooser objFilCho=new JFileChooser();
            objFilCho.setDialogTitle("Abrir");
            objFilCho.setFileSelectionMode(JFileChooser.FILES_ONLY);
            objFilCho.setCurrentDirectory(new File("C:\\"));
            //Filtrado (Opción 1):
            FileNameExtensionFilter objFilNamExt=new FileNameExtensionFilter("Archivos XLS", "xls");
            objFilCho.setFileFilter(objFilNamExt);
            //Filtrado (Opción 2):
    //        objFilCho.addChoosableFileFilter(new FileNameExtensionFilter("Archivos de texto", "txt"));
    //        objFilCho.addChoosableFileFilter(new FileNameExtensionFilter("Archivos java", "java"));
    //        objFilCho.addChoosableFileFilter(new FileNameExtensionFilter("Archivos php", "php", "php4", "phtml"));
            if (objFilCho.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)
            {
                strArc=objFilCho.getSelectedFile().getPath();
                //Si no tiene la extensión "txt" agregarsela.
    //            if (!strArc.toLowerCase().endsWith(".txt"))
    //                strArc+=".txt";

//                CarMaeVeh objCarMaeVeh=new CarMaeVeh();
//                dskGen.add(objCarMaeVeh, JLayeredPane.DEFAULT_LAYER);
//                objCarMaeVeh.setVisible(true);

                //abrirArcTex(strArc, ((MenArcBloNot)dskGen.getSelectedFrame()).txaPag);
                abrirArcXLS(strArc);
                this.setTitle(strArc);
    //            System.out.println("Directorio seleccionado: " + strArc);
    //            System.out.println("Texto: " + ((ifrProPal)dskGen.getSelectedFrame()).txaPag.getText());
            }
            else
            {
                System.out.println("El usuario canceló");
            }
        }
        catch(Exception e)
        {
            System.out.println("Excepción: " + e.toString());
            blnRes=false;
        }
        return blnRes;
    }
    
    private boolean abrirArcXLS(String strNomArc)
    {
        boolean blnRes=true;
        try
        {
            jxl.Workbook objWor=jxl.Workbook.getWorkbook(new java.io.File(strNomArc));
            jxl.Sheet objShe=objWor.getSheet("Hoja1");
            jxl.Cell objCel;
            vecNom.removeAllElements();
            vecMar.removeAllElements();
            for (int i=1; i<=objShe.getRows()-1; i++)
            {
                objCel=objShe.getCell(0, i);
                vecNom.add(objCel.getContents());
                objCel=objShe.getCell(1, i);
                vecMar.add(objCel.getContents());
            }
            objWor.close();
            lstNom.setListData(vecNom);
            lstMar.setListData(vecMar);
        }
        catch(Exception e)
        {
            System.out.println("Excepción: " + e.toString());
            blnRes=false;
        }
        return blnRes;
    }

    
}
